### PR TITLE
Add dark Mode Images

### PR DESCRIPTION
**Pull request by jsun1590**
## Change Summary
- Restructured json files to add links to dark mode images
- Added logic to switch images based on theme

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
Probably not the most efficient way to do this.

### CODE REVIEW

**Comment by CodeWithTheDoctor** [comment]
image

What's this xD?

I don't think you updated your branch with the latest changes from main/master...

Do `git checkout master` then do `git pull` then checkout to your branch again and do `get merge main` and then push the new changes

**Comment by jsun1590** [comment]
Bruh #1118 hasn't been merged yet

**Comment by CodeWithTheDoctor** [comment]
> Bruh #1118 hasn't been merged yet

Merged it!

**Comment by jsun1590** [comment]
@CodeWithTheDoctor Can review now

**Comment by CodeWithTheDoctor** [comment]
Awesome feature! But there is a bug!
jackshit

**Review by CodeWithTheDoctor — APPROVED** [review]
Looks good, Jack! 
Well done.

**Pull request merged**
